# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

name: Build Github runner image

on:
    schedule:
        - cron: "30 5 * * *"
    workflow_dispatch:

jobs:
    build_github_runner:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.CR_PAT }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./docker/Dockerfile.github-runner
                  push: true
                  tags: ghcr.io/slint-ui/slint/github-runner:latest
